"""Add user profile fields

Revision ID: 1ef0e9d8a490
Revises: 5dc1ddbc1827
Create Date: 2026-02-10 17:28:04.092027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef0e9d8a490'
down_revision = '5dc1ddbc1827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('recovery_key_hash', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('recovery_key_hash')
        batch_op.drop_column('profile_image')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
