"""Initial migration with user support

Revision ID: 5dc1ddbc1827
Revises: 
Create Date: 2026-02-10 16:04:58.767583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc1ddbc1827'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'user' not in existing_tables:
        op.create_table(
            'user',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('username', sa.String(length=64), nullable=False),
            sa.Column('email', sa.String(length=120), nullable=False),
            sa.Column('password_hash', sa.String(length=256), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
            sa.UniqueConstraint('email', name=op.f('uq_user_email')),
            sa.UniqueConstraint('username', name=op.f('uq_user_username')),
        )

    if 'finances' not in existing_tables:
        op.create_table(
            'finances',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('description', sa.String(length=100), nullable=False),
            sa.Column('value', sa.Float(), nullable=False),
            sa.Column('category', sa.String(length=50), nullable=False),
            sa.Column('type', sa.String(length=20), nullable=False),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('due_date', sa.Date(), nullable=False),
            sa.Column('payment_date', sa.Date(), nullable=True),
            sa.Column('observations', sa.Text(), nullable=True),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_finances_user_id_user')),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_finances')),
        )
        op.create_index('ix_finances_user_due_date', 'finances', ['user_id', 'due_date'], unique=False)
        op.create_index('ix_finances_user_type_status', 'finances', ['user_id', 'type', 'status'], unique=False)
    else:
        finance_columns = {column['name'] for column in inspector.get_columns('finances')}
        if 'user_id' not in finance_columns:
            with op.batch_alter_table('finances', schema=None) as batch_op:
                batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
                batch_op.create_foreign_key(batch_op.f('fk_finances_user_id_user'), 'user', ['user_id'], ['id'])

    if 'goals' not in existing_tables:
        op.create_table(
            'goals',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('target_amount', sa.Float(), nullable=False),
            sa.Column('current_amount', sa.Float(), nullable=True),
            sa.Column('deadline', sa.Date(), nullable=True),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_goals_user_id_user')),
            sa.PrimaryKeyConstraint('id', name=op.f('pk_goals')),
        )
        op.create_index('ix_goals_user_deadline', 'goals', ['user_id', 'deadline'], unique=False)
    else:
        goal_columns = {column['name'] for column in inspector.get_columns('goals')}
        if 'user_id' not in goal_columns:
            with op.batch_alter_table('goals', schema=None) as batch_op:
                batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
                batch_op.create_foreign_key(batch_op.f('fk_goals_user_id_user'), 'user', ['user_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_goals_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('finances', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_finances_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
